const EMAIL_PUBLIC_KEY = process.env.GATSBY_EMAIL_PUBLIC_KEY;
const EMAIL_SERVICE_ID = process.env.GATSBY_EMAIL_SERVICE_ID;
const EMAIL_TEMPLATE_ID = process.env.GATSBY_EMAIL_TEMPLATE_ID;

export { EMAIL_PUBLIC_KEY, EMAIL_TEMPLATE_ID, EMAIL_SERVICE_ID };
